# docker-compose.ymlフォーマットのバージョン
version: '3.4'
services:
  go:
    image: centos7
    build: .
    command: ["realize", "start"]
    # ローカルのsrcをコンテナにマウント
    volumes:
      - ./web:/go/src/github.com/web
    # コンテナの外部に3000番を公開
    # 公開するポート番号：コンテナ内部の転送先ポート番号
    ports:
      - 8080:8080
    # dbに起動
    depends_on:
      - db
    tty: true
    stdin_open: true
    networks:
      go_net:
        ipv4_address: 192.168.0.3
  # MySQLコンテナ定義
  db:
    # mysql8.0でコンテナ作成
    image: mysql:8.0
    volumes:
      # Mysql8.0のデフォルトの認証形式をmysql_native_passwordに設定
      - ./mysql-confd:/etc/mysql/conf.d
      # ローカルで保持しているDBをコンテナにマウント
      - db-volume:/var/lib/mysql
    # コンテナ内の環境変数を定義
    environment:
      # mysqlのルートユーザーのパスワード設定
      MYSQL_ROOT_PASSWORD: golang
      MYSQL_USER: golang
      MYSQL_PASSWORD: golang 
      MYSQL_DATABASE: golang
    ports:
      - "3306:3306"
    restart: 
      always
    networks:
      go_net:
        ipv4_address: 192.168.0.2

# DBの内容をローカルに保持
volumes:
  db-volume:

# ネットワーク
networks:
  go_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24